controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

address:
    path: api/address
    controller: App\Controller\AddressController::findAddress
    methods: ['GET']
